
#
# Script to read in a posterior distribution of trees generated by MrBayes,
# discard the first 5000 tree samples as burnin, and properly root the 
# remaining 15000 trees so they can be sampled while inferring phenotypic
# ancestral states.
#
# author: Will Freyman
#

library(ape)

input_trees = read.nexus("data/infile.nex.run1.t")

outgroup = c("Isoetes_coromandelina_ssp_macrotuberculata_Kim",
             "Isoetes_coromandelina_Hoot",
             "Isoetes_coromandelina_ssp_coromandelina_Kim",
             "Isoetes_coromandelina_ssp_macrotuberculata_egen",
             "Isoetes_schweinfurthii_6082_egen",
             "Isoetes_schweinfurthii_Rydin",
             "Isoetes_laosiensis_Kim",
             "Isoetes_cubana_Hoot",
             "Isoetes_jamaicensis_Hoot",
             "Isoetes_bradei_Rydin",
             "Isoetes_panamensis_egen",
             "Isoetes_panamensis_Hoot",
             "Isoetes_amazonica_Rydin",
             "Isoetes_australis_MR_Hoot",
             "Isoetes_australis_DR_Hoot",
             "Isoetes_australis_MM_Hoot",
             "Isoetes_capensis_Hoot",
             "Isoetes_stellenbossiensis_Hoot",
             "Isoetes_stellenbossiensis_egen",
             "Isoetes_toximontana_Hoot",
             "Isoetes_stephansenii_Hoot")

output_trees = list()
j = 1
burnin = 5000

for (i in burnin:length(input_trees)) {
    if (is.monophyletic(input_trees[[i]], outgroup)) {
        output_trees[[j]] = root(input_trees[[i]], outgroup)
        j = j + 1
    }
}

write.nexus(output_trees, file="data/rooted_trees.nexus")
